Algoritmo "semnome"

Var

Inicio

FUNÇÃO Soma(a, b)
RETORNAR a + b
FIM FUNÇÃO

FUNÇÃO Subtrair(a, b)
RETORNAR a - b
FIM FUNÇÃO

FUNÇÃO Multiplicar(a, b)
RETORNAR a * b
FIM FUNÇÃO

FUNÇÃO Dividir(a, b)
SE b ? 0
RETORNAR a / b
SENÃO
RETORNAR "Erro: Divisão por zero!"
FIM SE
FIM FUNÇÃO

IMPRIMIR Soma(2, 3)
IMPRIMIR Subtrair(5, 2)
IMPRIMIR Multiplicar(4, 5)
IMPRIMIR Dividir(10, 2)

Fimalgoritmo
